# Generated by Django 5.2.1 on 2025-05-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0002_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='treshold_quantity',
            field=models.PositiveBigIntegerField(default=1000, max_length=10),
        ),
    ]
